project:
  type: website
  output-dir: docs

website:
  title: "Joshua M. Rosenberg, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About and Contact
      - href: vita.html
        text: Vita
      - href: https://makingdatasciencecount.com/
        text: Research Group
      - href: https://joshuamrosenberg.substack.com/
        text: Newsletter/Blog
      - href: photography.qmd
        text: Photography

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    pdf-engine: xelatex

editor: visual

