project:
  type: website
  output-dir: docs

website:
  title: "Joshua M. Rosenberg, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: writing-and-photography.qmd
        text: Writing & Photography
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true
  pdf:
    pdf-engine: xelatex

editor: visual
resources:
  - CNAME
  - pdf/
